### ISSUE TITLE
The DOI pointing to the Roadmap is broken

### ISSUE THREAD

**Issue by slochower** [openforcefield/openforcefield.org#102]
The DOI link in this screenshot is broken. I'd submit a PR to fix, but I'm not actually sure where it should point.

![Screen Shot 2019-05-16 at 4 48 22 PM](https://user-images.githubusercontent.com/5393995/57894146-919c9c00-77fa-11e9-92b3-8f8cde1748a7.png)

Edit: it points to 10.0.51.84/RG.2.2.27587.86562.

**Comment by slochower** [comment]
Maybe to this: 10.13140/RG.2.2.27587.86562?

**Comment by j-wags** [comment]
That looks correct, @slochower. 

The link right now is a raw DOI which doesn't resolve to a real page in my browser. Maybe we can update it to dx.doi.org/10.13140/RG.2.2.27587.86562

**Comment by j-wags** [comment]
@karmencj, would you be up to try this fix tomorrow?

**Comment by karmencj** [comment]
Yes!`I might migrate it first to Zenodo and get a DOI there, now that I have (almost) functional email.

**Comment by karmencj** [comment]
Fixed! It took a bit longer than expected because getting the Zenodo community up took a bit longer than expected! The new DOI is http://doi.org/10.5281/zenodo.3228414.

**Comment by slochower** [comment]
Looks good to me. I'll update my citation. Thanks!
