### ISSUE TITLE
Broken link pointing to SMIRNOFF documentation (Force fields page)

### ISSUE THREAD

**Issue by karmencj** [openforcefield/openforcefield.org#114]
The link pointing to SMIRNOFF documentation on RTD is now broken. I assume it should be replaced with this one: https://open-forcefield-toolkit.readthedocs.io/en/0.3.0/smirnoff.html.

@j-wags, can you confirm?

![image](https://user-images.githubusercontent.com/32760282/58603100-751e4c00-825d-11e9-85e5-7fd5ef55c822.png)

**Comment by j-wags** [comment]
Yes, that's correct. Great catch!
