### ISSUE TITLE
Where to put info on events, meeting minutes?

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openforcefield.org#20]
Where should we put info on upcoming events? Should we have a dedicated tab?

Also, what about meeting minutes? We're required to post these for Consortium meetings. Link to them from under `Consortium`?

(Also discussing on Slack, but putting it here for the record.)

**Comment by davidlmobley** [comment]
@leeping any thoughts on this? I need to get the minutes from last meeting up. :)

**Comment by leeping** [comment]
Thanks for the reminder.  Could we create a new top-level menu item called "Meetings & Events"?  We can clone @jchodera 's science update infrastructure for posting meeting minutes.

**Comment by jchodera** [comment]
How about just "Events" to keep with the style of everything else?

**Comment by leeping** [comment]
Is it clear enough that meeting minutes would be located under Events?

**Comment by jchodera** [comment]
I think Consortium information---like governance documents and meeting minutes---should be under the "Consortium" menu item.

**Comment by leeping** [comment]
Okay. Upcoming events under a new menu item "Events", and meeting minutes under "Consortium" is fine with me. @davidlmobley what do you think?
