### ISSUE TITLE
Parsley blog post

### ISSUE THREAD

**Issue by wutobias** [openforcefield/openforcefield.org#209]
Hi,

in the blog post on the release of Parsley (https://openforcefield.org/news/introducing-openforcefield-1.0/) the regularization penalty weight w_reg is introduced, but does not show up in the equations (see section "Regularized force field optimization with quasi-Newton iterations"). I think it should be in front of the regularization term. Or does it maybe refer to something else from the original ForceBalance work?

Regards,
Tobias

**Comment by j-wags** [comment]
@wutobias had shown this to me earlier, and I think it may be a typo left over from an initial draft? 

To clarify -- The highlighted sentence in the image below defines a term `w_reg`, which doesn't appear in any equations. He thinks (and I agree) that it should most likely be in the first equation, inside the second summation. I'm happy to open a PR for this if so.

![Screen Shot 2019-12-11 at 4 45 16 PM](https://user-images.githubusercontent.com/16329175/70672977-db5a4180-1c78-11ea-9f6c-354f1ddf2972.png)
