### ISSUE TITLE
Should we remove the software scientist position?

### ISSUE THREAD

**Issue by mrshirts** [openforcefield/openforcefield.org#228]
Seems like with Dotson and Thompson working now, and lack of $$$, we may want to remove the software scientist ad. Or do we leave it on just in case we get more funding 3-4 months from now?

**Comment by davidlmobley** [comment]
I'm torn. I think either.

(Probably most of us get bheind on GitHub notifications, so probably cross-post link to your issue in Slack for faster response.)

**Comment by karmencj** [comment]
I decided to remove it for now, but we can always bring it back later if needed. I concluded that for now we won't be able to hire another SS.
