### ISSUE TITLE
Missing TeX rendering?

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openforcefield.org#286]
New website looks great - just encountering some missing TeX, if that wasn't already caught. I'm on a slow internet connection so it could be on my end, but I did try 3 different hardware (Firefox on Linux, Chrome on Windows, and an Android phone)

https://openforcefield.org/community/news/news/introducing-openforcefield-1.0/

![image](https://user-images.githubusercontent.com/7935382/91193075-5440e280-e6bc-11ea-97d3-4037f19ebbe3.png)

**Comment by karmencj** [comment]
This was fixed a while ago in #295, I haven't checked the issues until now.
