### ISSUE TITLE
Line spacing in numbered lists and bulleted lists is too large

### ISSUE THREAD

**Issue by leeping** [openforcefield/openforcefield.org#31]
The attached screenshot is what I'm seeing.  I did not add any extra line breaks in the source.

I think style sheet needs to be updated but not sure how.

(Screenshot below)

<img width="694" alt="screenshot 2018-10-19 10 44 48" src="https://user-images.githubusercontent.com/1441560/47234860-0c4c2880-d38c-11e8-9823-1642cf560721.png">

**Comment by jchodera** [comment]
Addressed (at least to some degree!) in #61.
