### ISSUE TITLE
Shorter paths to installation instructions

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openforcefield.org#332]
There are many clicks between the homepage and installation instructions for any packages (say, the toolkit)

 > Here's what I see as the minimum path: openforcefield.org → software → scroll to OpenFF toolkit → GitHub → scroll all the way down to "Detailed installation instructions can be found here."

It may be better to have shortcuts to installation instructions on https://openforcefield.org/software/, something like below; even if that is just a box that points to the installation instructions in the docs, it shortens the path

![image](https://user-images.githubusercontent.com/7935382/104652272-7d1f3f80-567e-11eb-8a59-ba662378c498.png)

**Comment by karmencj** [comment]
Resolved.
