### ISSUE TITLE
Remove Josh Fass from Team?

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openforcefield.org#335]
@maxentile : Should we remove you from the [Team](https://openforcefield.org/about/team/) page?

We could move you to an "External Collaborator" if you prefer!

**Comment by maxentile** [comment]
Ahh, yes, this is out of date! Updating to Alumni (and preferably also to External Collaborators) would be ideal.

**Comment by karmencj** [comment]
Fixed here: https://github.com/openforcefield/openforcefield.org/pull/338
