### ISSUE TITLE
Add anchor tag to Consortium info or Consortium members, or split into separate web page?

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openforcefield.org#346]
I often want to point someone to the current Consortium members, an explanation of the Consortium, or info on how to join the Consortium, but the way the current website is organized, this is impossible. 

Can we either add anchor tags to make it possible to link this information directly, or somehow split off the Consortium information? The current division of information does not make it easy to recruit new partners.

**Comment by jchodera** [comment]
@karmencj : Any thoughts on this?

**Comment by karmencj** [comment]
You can point to the Consortium: https://openforcefield.org/about/organization/#open-force-field-consortium 
or just the list of industry partners: https://openforcefield.org/about/organization/#industry-partners.

But, the section doesn't really provide a lot of information about how to join. I will include more details when we get the process sorted with the OMSF. I have a list of planned changes and improvements for the website, but it's not my priority at the moment.
