### ISSUE TITLE
Advisory board meeting minutes are out of date

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield.org#383]
Our landing page links to https://openforcefield.org/minutes/cab/, which hasn't been updated since 2020. Maybe we should link directly to the Google doc?

Would there be any security/privacy concerns by doing this? (For the record, I switched that doc from "anyone with the link can edit" to "anyone with the link can view", and gave explicit edit permission to project leadership)

**Comment by karmencj** [comment]
@diegoonolasco, could you update the entries on the website when you find a moment?

**Comment by diegoonolasco** [comment]
Sure! I'll start the job right now.

**Comment by j-wags** [comment]
I just reviewed #391 (which looks great) but I'm realizing a few things:

* From my experience, writing meeting minutes takes _forever_, like usually more time than the meeting itself.
* #391 starts a scary story (the Anaconda licensing thing), but it's actually resolved in later months. Someone who just glances at these meeting notes would be spooked, even though we _know_ that this ends happily. So I think we could use more flexibility in handling the ad board minutes backlog.
* There's a lot of repeated process delays that we'll encounter if we try to make monthly summaries (formatting easy-to-mess-up fields, requesting review, etc)

So, I'd advocate that we handle the ad board backlog with a few quarterly or semiannual (or even just annual) summaries. 

Also, future ad board minutes could be monthly or quarterly, at @diegoonolasco's discretion. 

@karmencj does this sound like a good course of action?

**Comment by diegoonolasco** [comment]
The cab meeting minutes are up to date.

**Comment by diegoonolasco** [comment]
In time... @karmencj, thanks for the task. It was a fantastic opportunity to go over a lot of very important information. @j-wags, thanks for reviewing each and every PR, and thanks for all the edits and suggestions.

**Comment by j-wags** [comment]
I totally missed that this was getting closed. Congratulations, Diego!! This was a big, visible piece of org debt and you totally knocked it out! 🎉 ⚾ 🏆 !!!
