### ISSUE TITLE
Broken news link

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openforcefield.org#426]
Perhaps related to #310, although not the same -- I think some rearrangement has broken news links again. The link at https://openforcefield.org/about/organization/ to `https://openforcefield.org/community/news/news/introducing-the-consortium/` should probably direct to `https://openforcefield.org/community/news/general/introducing-the-consortium/` instead.

**Comment by j-wags** [comment]
I'd happily accept a PR fixing this!
