### ISSUE TITLE
Update remaining Travis CI to use GitHub Actions

### ISSUE THREAD

**Issue by Yoshanuikabundi** [openforcefield/openforcefield.org#445]
PRs cause a failing status because they try to build the PR with Travis. We should update this to remove any reference to Travis and convert as much as possible to GHA - There's a prototype of this at https://github.com/openforcefield/openff-sphinx-theme/blob/main/.github/workflows/gh_pages.yml

**Comment by mikemhenry** [comment]
I've updated the repo to use a github action that uses hugo to build the site, and then uses the new "build page from action" feature https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/
