### ISSUE TITLE
Better landing page?

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openforcefield.org#92]
The [TensorFlow Core overview page](https://www.tensorflow.org/overview/) is a great example of a very helpful landing page:
![image](https://user-images.githubusercontent.com/3656088/56096860-56d1dc00-5ebb-11e9-90f9-d31d7b409e6b.png)
* Menu at top with useful major links
* Tabs with most immediate information on Overview, Tutorial, Docs, coming features
* Link to upcoming meetings
* Prominent buttons for tutorials and docs
* Illustrative code snippets with buttons to run the full example from your browser

**Comment by karmencj** [comment]
Closing this issue for now since we redesigned the website in the meantime.
